### ISSUE TITLE
Segfault on Linux after jumping to a new beacon

### ISSUE THREAD

**Issue by limelier** [FTL-Hyperspace/FTL-Hyperspace#393]
Hi, 

I've been playing FTL MV on Linux for a while, and quite often - about once every run, basically - upon jumping to a new beacon, the game will crash. Then, when launching it again, the game will either crash again when I jump to any beacon (and delete the continue file), or not crash again. I'm not sure what causes the two different cases to happen - it's probably either running the game through steam vs through the CLI, or running on an Nvidia GPU vs an AMD one.

## Running the game through steam
When running the game through steam, the logs and trace aren't very helpful. Here's my logs from a run through steam where my save file was deleted upon the second crash:
[FTL_HS.log](https://github.com/user-attachments/files/17787990/FTL_HS.log)
[FTL.log](https://github.com/user-attachments/files/17787991/FTL.log)

Running `sudo coredumpctl debug -1` followed by `bt` yields the following stack trace:
```
#0  0x000079331c8a53f4 in ?? ()
#1  0x0000000000409220 in XSetICFocus@plt ()
#2  0xca2391cbbc1c4d00 in ?? ()
#3  0x0000000000000000 in ?? ()
```

## Running the game from the command-line
Launching the game directly from the CLI, I can get more helpful logs and traces. Here's the last few lines of a log from a recent such run, following a crash (of the second kind, did not repeat on a retry):
```
UpdateLocation - LocationEvent Seen, name: FUSION_ONCREWZERO
Fetching 0 on_game_event callbacks for FUSION_ONCREWZERO
Something went wrong in saving the profile!
Something went wrong in saving the profile!
double free or corruption (out)
fish: Job 1, './FTL' terminated by signal SIGABRT (Abort)
```

Here's the stack trace:
```
(gdb) bt
#0  0x0000728aa67b63f4 in ?? () from /usr/lib/libc.so.6
#1  0x0000728aa675d120 in raise () from /usr/lib/libc.so.6
#2  0x0000728aa67444c3 in abort () from /usr/lib/libc.so.6
#3  0x0000728aa6745354 in ?? () from /usr/lib/libc.so.6
#4  0x0000728aa67c0765 in ?? () from /usr/lib/libc.so.6
#5  0x0000728aa67c29f0 in ?? () from /usr/lib/libc.so.6
#6  0x0000728aa67c2cfa in ?? () from /usr/lib/libc.so.6
#7  0x0000728aa67c55ce in free () from /usr/lib/libc.so.6
#8  0x0000000000644b14 in __gnu_cxx::new_allocator<float>::deallocate (this=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.8/ext/new_allocator.h:110
#9  std::_Vector_base<float, std::allocator<float> >::_M_deallocate (this=<optimized out>, __n=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.8/bits/stl_vector.h:174
#10 std::_Vector_base<float, std::allocator<float> >::~_Vector_base (this=0x3af80c58, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/stl_vector.h:160
#11 std::vector<float, std::allocator<float> >::~vector (this=0x3af80c58, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/stl_vector.h:416
#12 OxygenSystem::~OxygenSystem (this=0x3af80a10, __in_chrg=<optimized out>) at /media/sf_FTL/Project/src/Ship/ShipSystems/OxygenSystem.h:30
#13 OxygenSystem::~OxygenSystem (this=0x3af80a10, __in_chrg=<optimized out>) at /media/sf_FTL/Project/src/Ship/ShipSystems/OxygenSystem.h:30
#14 0x00000000004b9a34 in ShipManager::OnCleanup (this=this@entry=0x2b0cdcc0) at /media/sf_FTL/Project/src/Ship/ShipManager.cpp:3859
#15 0x00000000004cec17 in ShipManager::~ShipManager (this=0x2b0cdcc0, __in_chrg=<optimized out>) at /media/sf_FTL/Project/src/Ship/ShipManager.cpp:75
#16 0x00000000004ceec9 in ShipManager::~ShipManager (this=0x2b0cdcc0, __in_chrg=<optimized out>) at /media/sf_FTL/Project/src/Ship/ShipManager.cpp:78
#17 0x00000000004215ea in CompleteShip::~CompleteShip (this=0x3a975630, __in_chrg=<optimized out>) at /media/sf_FTL/Project/src/CompleteShip.cpp:304
#18 0x00000000004216c9 in CompleteShip::~CompleteShip (this=0x3a975630, __in_chrg=<optimized out>) at /media/sf_FTL/Project/src/CompleteShip.cpp:305
#19 0x0000000000633b7a in WorldManager::ClearLocation (this=0x3c7c6df0) at /media/sf_FTL/Project/src/Gameplay/World/WorldManager.cpp:1206
#20 0x0000728aa7634350 in (anonymous namespace)::Hook_280::wrapper::hook() () from /home/lime/.local/share/Steam/steamapps/common/FTL Faster Than Light/data/Hyperspace.1.6.13.amd64.so
#21 0x0000728aa7764c6d in (anonymous namespace)::Hook_263::wrapper::hook() () from /home/lime/.local/share/Steam/steamapps/common/FTL Faster Than Light/data/Hyperspace.1.6.13.amd64.so
#22 0x0000000000635751 in WorldManager::CheckForNewLocation (this=0x3c7c6df0, savingGame=<optimized out>) at /media/sf_FTL/Project/src/Gameplay/World/WorldManager.cpp:1680
#23 0x0000000000636b1b in WorldManager::OnLoop (this=0x3c7c6df0) at /media/sf_FTL/Project/src/Gameplay/World/WorldManager.cpp:1692
#24 0x0000728aa766854c in (anonymous namespace)::Hook_3695::wrapper::hook() () from /home/lime/.local/share/Steam/steamapps/common/FTL Faster Than Light/data/Hyperspace.1.6.13.amd64.so
#25 0x0000728aa76be538 in (anonymous namespace)::Hook_6558::wrapper::hook() () from /home/lime/.local/share/Steam/steamapps/common/FTL Faster Than Light/data/Hyperspace.1.6.13.amd64.so
#26 0x0000728aa780d48c in (anonymous namespace)::Hook_1486::wrapper::hook() () from /home/lime/.local/share/Steam/steamapps/common/FTL Faster Than Light/data/Hyperspace.1.6.13.amd64.so
#27 0x000000000041bede in CApp::OnLoop (this=0x7ffc1c200cd0) at /media/sf_FTL/Project/src/CApp.cpp:778
#28 0x0000728aa76be7ff in (anonymous namespace)::Hook_6623::wrapper::hook() () from /home/lime/.local/share/Steam/steamapps/common/FTL Faster Than Light/data/Hyperspace.1.6.13.amd64.so
#29 0x0000728aa778e916 in (anonymous namespace)::Hook_1016::wrapper::hook() () from /home/lime/.local/share/Steam/steamapps/common/FTL Faster Than Light/data/Hyperspace.1.6.13.amd64.so
#30 0x000000000041d7f0 in CApp::OnExecute (this=this@entry=0x7ffc1c200cd0) at /media/sf_FTL/Project/src/CApp.cpp:505
#31 0x000000000041ef52 in sil_main (argc=argc@entry=1, argv=argv@entry=0x7ffc1c204938) at /media/sf_FTL/Project/src/CApp.cpp:678
#32 0x000000000065e8c8 in sil__main (argc=argc@entry=1, argv=argv@entry=0x7ffc1c204938) at /media/sf_FTL/Project/lib/SIL/src/main.c:106
#33 0x0000000000418805 in main (argc=1, argv_=<optimized out>) at /media/sf_FTL/Project/lib/SIL/src/sysdep/linux/main.c:152
```

## Other info
I'm running Hyperspace 1.15.0. I'm on Arch Linux, and this issue has occurred with multiple kernel versions, drivers and GPUs. 
Here's the mod list/order:
![image](https://github.com/user-attachments/assets/ea7f9df4-3142-4f6a-adcb-05a9c62c3ae6)

**Comment by sy-python** [comment]
I am experiencing the same issue. Have you discovered any temporary remedy?

**Comment by limelier** [comment]
My current work around is to use the Windows version of FTL through Proton instead of the native Linux version.

-------- Original Message --------

**Comment by sy-python** [comment]
Has there been any progress on this btw?
